print('Nama  : Muhammad Rifqi Hidayat')
print('NPM   : 2210010126\n')
print('\n')
print("Program Penampil Data Diri")
print("**************************")
nama = input("Masukan Nama :")
alamat = input("Masukan Alamat :")
hobby = input("Masukan Hobby :")
print("Hallo",nama,"!!!","Kamu Tinggal di",alamat,"dan hobby mu adalah",hobby)